jdk:
  - openjdk11
install:
  - echo "Jitpack is not supported. No kadx release is published to Maven Central yet; check usage help at https://github.com/skylot/jadx/wiki/Use-jadx-as-a-library"
  - ./gradlew intentional-fail
