package jadx.tests.integration.inline;

import java.util.List;
import java.util.Map;
import java.util.function.Function;

public class TestInstanceLambdaFixture {

	@SuppressWarnings({ "unchecked", "rawtypes", "SameParameterValue" })
	public static class TestCls {

		public <T> Map<T, T> test(List<? extends T> list) {
			return toMap(list, Lambda$1.INSTANCE);
		}

		/**
		 * Smali test missing 'T' definition in 'Lambda<T>'
		 * Note: use '$1' so class looks like generated by compiler and pass check in
		 * {@link jadx.core.dex.visitors.ProcessAnonymous#canBeAnonymous(jadx.core.dex.nodes.ClassNode)}
		 */
		@SuppressWarnings({ "CheckStyle", "checkstyle:TypeName" })
		private static class Lambda$1<T> implements Function<T, T> {
			public static final Lambda$1 INSTANCE = new Lambda$1();

			@Override
			public T apply(T t) {
				return t;
			}
		}

		private static <T> Map<T, T> toMap(List<? extends T> list, Function<T, T> valueMap) {
			return null;
		}
	}
}
