package jadx.tests.integration.inline

import jadx.core.dex.nodes.MethodNode
import jadx.tests.api.IntegrationTest
import jadx.tests.api.extensions.profiles.TestProfile
import jadx.tests.api.extensions.profiles.TestWithProfiles
import jadx.tests.api.utils.assertj.JadxAssertions.assertThat
import org.assertj.core.api.Condition
import org.junit.jupiter.api.Test

/**
 * 泛型内部类的 bridge 方法：`IntInner.get` 不应被重命名（如 `mo0get`），调用点保持 `get`。
 */
class TestSyntheticBridgeRename : IntegrationTest() {

	@TestWithProfiles(TestProfile.DX_J8, TestProfile.JAVA8)
	fun test() {
		val cls = getClassNode(TestSyntheticBridgeRenameFixture.TestCls::class.java)
		assertThat(searchCls(cls.innerClasses, "IntInner").methods)
			.`as`("check that bridge method was generated by compiler")
			.haveAtLeastOne(Condition<MethodNode>({ mth -> mth.accessFlags.isBridge() }, "bridge"))

		assertThat(cls)
			.code()
			.doesNotContain("mo0get")
			.containsOne("call(inner.get(\"a\"));")
	}
}
