package jadx.core.utils.android

import jadx.api.ICodeWriter
import jadx.api.plugins.input.data.AccessFlags
import jadx.api.plugins.input.data.annotations.EncodedType
import jadx.api.plugins.input.data.annotations.EncodedValue
import jadx.core.codegen.ClassGen
import jadx.core.deobf.NameMapper
import jadx.core.dex.attributes.AFlag
import jadx.core.dex.info.ClassInfo
import jadx.core.dex.info.ConstStorage
import jadx.core.dex.info.FieldInfo
import jadx.core.dex.instructions.args.ArgType
import jadx.core.dex.nodes.ClassNode
import jadx.core.dex.nodes.FieldNode
import jadx.core.dex.nodes.RootNode
import jadx.core.xmlgen.ResourceStorage
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.util.HashMap
import java.util.TreeMap

/**
 * Android 资源（`R` 类）相关的辅助逻辑。
 *
 * **用途**：
 * 1. 在反编译结果中定位或合成应用的 `R` 类；
 * 2. 把 `resources.arsc` 里解析出的资源条目补成 `R.<type>.<name>` 常量字段；
 * 3. 判断某个字段/类是否属于资源类，从而决定是否强制输出 16 进制 id。
 *
 * **Kotlin 转换说明**：
 * - 全部为静态方法，用 `object` + `@JvmStatic` 保持 Java 调用 `AndroidResourcesUtils.xxx(...)` 不变；
 * - 内部辅助类 [ResClsInfo] 与私有方法保持实现细节；
 * - 访问已 Kotlin 化的 [ClassNode]/[FieldNode]/[ClassInfo] 时使用属性语法（如 `.parentClass`/`.alias`）。
 */
object AndroidResourcesUtils {

	private val LOG: Logger = LoggerFactory.getLogger(AndroidResourcesUtils::class.java)

	/**
	 * 定位应用的 `R` 类：优先按“应用包名.R”查找；找不到再按短名 `R` 唯一候选查找；
	 * 实在没有则合成一个 `R` 类并把资源字段补进去。
	 */
	@JvmStatic
	fun searchAppResClass(root: RootNode, resStorage: ResourceStorage): ClassNode {
		val appPackage = root.getAppPackage()
		val fullName = if (appPackage != null) "$appPackage.R" else "R"
		val clsInfo = ClassInfo.fromName(root, fullName)
		val resCls = root.resolveClass(clsInfo)
		if (resCls != null) {
			addResourceFields(resCls, resStorage, true)
			return resCls
		}
		LOG.debug("Can't find 'R' class in app package: {}", appPackage)
		val candidates = root.searchClassByShortName("R")
		if (candidates.size == 1) {
			val resClsCandidate = candidates[0]
			addResourceFields(resClsCandidate, resStorage, true)
			return resClsCandidate
		}
		if (candidates.isNotEmpty()) {
			LOG.info("Found several 'R' class candidates: {}", candidates)
		}
		LOG.info("App 'R' class not found, put all resources ids into : '{}'", fullName)
		val rCls = ClassNode.addSyntheticClass(root, clsInfo, AccessFlags.PUBLIC or AccessFlags.FINAL)
		rCls.addInfoComment("This class is generated by JADX")
		addResourceFields(rCls, resStorage, false)
		return rCls
	}

	/** 处理对 `R` 内部类字段的引用：若声明类是 `R` 的内部类，则用“R.短名”形式输出。 */
	@JvmStatic
	fun handleAppResField(code: ICodeWriter, clsGen: ClassGen, declClass: ClassInfo): Boolean {
		val parentClass = declClass.parentClass
		if (parentClass != null && parentClass.shortName == "R") {
			clsGen.useClass(code, parentClass)
			code.add('.')
			code.add(declClass.aliasShortName)
			return true
		}
		return false
	}

	/** 资源类里的 int 字段强制用 16 进制输出（资源 id 可读性更好）。 */
	@JvmStatic
	fun isResourceFieldValue(cls: ClassNode, type: ArgType): Boolean = type == ArgType.INT && isResourceClass(cls)

	/** 判断该类是否是 `R` 的内部类（其父类别名为 `R`）。 */
	@JvmStatic
	fun isResourceClass(cls: ClassNode): Boolean = cls.parentClass.alias == "R"

	/** 某个资源类型（`R.string`/`R.drawable` 等）对应的内部类及其已有字段映射。 */
	private class ResClsInfo(val typeCls: ClassNode) {
		val fieldsMap: MutableMap<String, FieldNode> = HashMap()
	}

	/**
	 * 把 [ResourceStorage] 中的资源条目补成 `R` 类字段。
	 *
	 * @param rClsExists 是否已存在真实 `R` 类（false 表示当前是合成的，字段不做重命名）
	 */
	private fun addResourceFields(resCls: ClassNode, resStorage: ResourceStorage, rClsExists: Boolean) {
		val resFieldsMap = fillResFieldsMap(resCls)
		val innerClsMap = TreeMap<String, ResClsInfo>()
		if (rClsExists) {
			for (innerClass in resCls.innerClasses) {
				val innerResCls = ResClsInfo(innerClass)
				innerClass.fields.forEach { field -> innerResCls.fieldsMap[field.getName()] = field }
				innerClsMap[innerClass.alias] = innerResCls
			}
		}
		for (resource in resStorage.getResources()) {
			val resTypeName = resource.getTypeName()
			val resName = resource.getKeyName().replace('.', '_')

			val typeClsInfo = innerClsMap.getOrPut(resTypeName) {
				getClassForResType(resCls, rClsExists, resTypeName)
			}
			typeClsInfo.fieldsMap.getOrPut(resName) {
				val typeCls = typeClsInfo.typeCls
				val rFieldInfo = FieldInfo.from(typeCls.root(), typeCls.classInfo, resName, ArgType.INT)
				val newResField = FieldNode(
					typeCls,
					rFieldInfo,
					AccessFlags.PUBLIC or AccessFlags.STATIC or AccessFlags.FINAL,
				)
				newResField.addAttr(EncodedValue(EncodedType.ENCODED_INT, resource.getId()))
				typeCls.addField(newResField)
				if (rClsExists) {
					newResField.addInfoComment("Added by JADX")
				}
				newResField
			}
			val fieldNode = resFieldsMap[resource.getId()]
			if (fieldNode != null &&
				fieldNode.getName() != resName &&
				NameMapper.isValidAndPrintable(resName) &&
				resCls.root().getArgs().isRenameValid()
			) {
				fieldNode.add(AFlag.DONT_RENAME)
				fieldNode.getFieldInfo().alias = resName
			}
		}
	}

	/** 获取资源类型（如 `string`）对应的内部类；已存在则复用，否则合成一个新类。 */
	private fun getClassForResType(resCls: ClassNode, rClsExists: Boolean, typeName: String): ResClsInfo {
		val root = resCls.root()
		val typeClsFullName = resCls.classInfo.makeRawFullName() + '$' + typeName
		val clsInfo = ClassInfo.fromName(root, typeClsFullName)
		val existCls = root.resolveClass(clsInfo)
		if (existCls != null) {
			val resClsInfo = ResClsInfo(existCls)
			existCls.fields.forEach { field -> resClsInfo.fieldsMap[field.getName()] = field }
			return resClsInfo
		}
		val newTypeCls = ClassNode.addSyntheticClass(
			root,
			clsInfo,
			AccessFlags.PUBLIC or AccessFlags.STATIC or AccessFlags.FINAL,
		)
		if (rClsExists) {
			newTypeCls.addInfoComment("Added by JADX")
		}
		return ResClsInfo(newTypeCls)
	}

	/** 收集全局常量表中“public static final int”字段，按数值建立索引，用于后续重命名匹配。 */
	private fun fillResFieldsMap(resCls: ClassNode): MutableMap<Int, FieldNode> {
		val resFieldsMap = HashMap<Int, FieldNode>()
		val constStorage: ConstStorage = resCls.root().getConstValues()
		constStorage.getGlobalConstFields().forEach { (key, field) ->
			if (field.getFieldInfo().type == ArgType.INT &&
				field is FieldNode &&
				key is Int
			) {
				val accessFlags = field.accessFlags
				if (accessFlags.isStatic() && accessFlags.isFinal()) {
					resFieldsMap[key] = field
				}
			}
		}
		return resFieldsMap
	}
}
